# Example workflow
name: Format

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      # Recommended: latest versions of Google Java Format require JDK 11+
        with:
          repo-token: 64fc0621feb10dbdf02e9494de92184aef2b74a6
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"